POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJpZ0d1eSIsImlkIjoiNjQ3YjExMmUxNmU3NDE0NmMwZGZmNjgyIiwiaWF0IjoxNjg1Nzg3MTU1fQ.nUbc0cnpZ7V1FyjTF5sMdNcUoDKkUPvIRWvCh3-POw4

{
    "title":"Learning about learning",
    "author":"Oakley",
    "url":"memorybuilder.com",
    "likes":91105
}